nextcloud_install: True
nextcloud_enabled: False

nextcloud_url: /nextcloud
owncloud_prefix: /opt
nextcloud_data_dir: /library/nextcloud/data
nextcloud_dl_url: https://download.nextcloud.com/server/releases/
nextcloud_src_file: latest-11.tar.bz2

# we install on mysql with these setting or those from default_vars, etc.
nextcloud_dbname: nextcloud
nextcloud_dbhost: localhost
nextcloud_dbuser: nextcloud
owncloud_dbpassword: nextcloudmysql

nextcloud_admin_user: 'Admin'
nextcloud_admin_password: 'changeme'

nextcloud_required_ip: 10.0.0.0/8 192.168.0.0/16
